PERSON_1_ID: int = 1
PERSON_1_NAME = 'John'
PERSON_1_FAVORITE_SPORT = 'Basketball'
PERSON_2_ID: int = 2
PERSON_2_NAME = 'Sara'
PERSON_2_LAST_NAME = 'Wills'
PERSON_2_AGE = 28
PERSON_2_FAVORITE_SPORT = 'Climbing'
