variable "env_name" {}
variable "availability_zones" {}
variable "cidr_blocks_object" {}
variable "target_group_type" {}
variable "container_port" {}
variable "lb_type" {}
variable "domain" {}
variable "container_name" {}
variable "host_port" {}
variable "replicas" {}
variable "docker_image" {}
variable "ecs_family" {}
variable "ecs_launch_type" {}
variable "region" {}
variable "sub_domain" {}
