on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AVAILABILITY_ZONES: ${{ secrets.AVAILABILITY_ZONES }}
  CIDR_BLOCKS_OBJECT: ${{ secrets.CIDR_BLOCKS_OBJECT }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  DOMAIN: ${{ secrets.DOMAIN }}
  ECS_FAMILY: ${{ secrets.ECS_FAMILY }}
  ECS_LAUNCH_TYPE: ${{ secrets.ECS_LAUNCH_TYPE }}
  ENV_NAME: ${{ secrets.ENV_NAME }}
  HOST_PORT: ${{ secrets.HOST_PORT }}
  LB_TYPE: ${{ secrets.LB_TYPE }}
  REGION: ${{ secrets.REGION }}
  REPLICAS: ${{ secrets.REPLICAS }}
  SUB_DOMAIN: ${{ secrets.SUB_DOMAIN }}
  TARGET_GROUP_TYPE: ${{ secrets.TARGET_GROUP_TYPE }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build_and_deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}
      - name: login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      - name: Build Docker Image
        run: |
          echo "build docker image from current code"
          docker build -f Dockerfile -t ${{ env.DOCKER_IMAGE }}
      - name: Push image to DockerHub
        run: |
          echo "pushing image to DockerHub"
          docker push ${{ env.DOCKER_IMAGE }}
      - name: navigate to terraform staging directory
        run: cd infrastructure/terraform/environments/staging
      - name: configure Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 5.34.0
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan
      - name: Terraform apply
        run: terraform apply --auto-approve

  test:
    runs-on: ubuntu-latest
    needs: build_and_deploy_to_staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.11'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run api tests
        run: python -m pytest
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-results-allure-report
          path: allure-results/
          retention-days: 30
      - name: deploy allure report to github pages
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
    
  destory_resources:
    runs-on: ubuntu-latest
    needs: [build_and_deploy_to_staging, test]
    steps:
      - uses: action/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET_KEY }}
          aws-region: ${{ env.REGION }}
      - name: navigate to terraform staging directory
        run: cd infrastructure/terraform/environments/staging
      - name: configure Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 5.34.0
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform destory
        run: terraform destroy --auto-approve
        

        





        



